apiVersion: v2
name: websub
description: A Helm chart for WebSub
type: application
version: 0.0.0-develop
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.x.x
- name: kafka
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 29.x.x
  condition: kafka.enabled
keywords:
  - mosip
  - websub
maintainers:
  - email: info@openg2p.org
    name: OpenG2P
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "WebSub"
