{{- if .Values.consolidator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-consolidator
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.consolidator.service.type }}
  {{- if (or (eq .Values.consolidator.service.type "LoadBalancer") (eq .Values.consolidator.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.consolidator.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.consolidator.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.consolidator.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.consolidator.service.type "LoadBalancer") (not (empty .Values.consolidator.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.consolidator.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.consolidator.service.port }}
      targetPort: {{ .Values.consolidator.containerPort }}
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.consolidator.podLabels "context" $) | nindent 4 }}
{{- end }}
