[package]
org = "mosip"
name = "consolidatorService"
version = "0.0.0-SNAPSHOT"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
modules = ["inittopic"]
groupId = "io.mosip"
artifactId = "kafka-admin-client"
version = "0.0.0-SNAPSHOT"
path = "../kafka-admin-client/target/kafka-admin-client-0.0.0-SNAPSHOT.jar"
